title: Aaron's Blog
description: "A collection of thoughts as I strive to be a better developer"
author:
  name: "Aaron Young"
  email: "hi@aaronyoung.io"
  url: "https://old-blog.aaronyoung.io"

baseurl: /

source: .
destination: ./docs
permalink: /:title
paginate: 5
paginate_path: /page/:num/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner: "AaronYoung"
year: "2020"
